apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: mgmt
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-httpbin'
    spec:
      project: default
      source:
        repoURL: https://github.com/ably77/idp-project
        targetRevision: HEAD
        path: applications/
      destination:
        server: '{{url}}'